@echo off
chcp 65001 >nul
title Telegram Downloader - TDL GUI Generated

echo ========================================
echo  Telegram Downloader
echo  Generated by TDL GUI
echo ========================================
echo.
echo Command to execute:
echo bin\tdl dl -l 2 -n default --pool 8 --proxy socks5://127.0.0.1:7897 --reconnect-timeout 5m0s -t 4 -u https://t.me/c/3081142751/2970 -d G:\Software\TDL\downloads --skip-same
echo.
echo Starting download...
echo.

bin\tdl dl -l 2 -n default --pool 8 --proxy socks5://127.0.0.1:7897 --reconnect-timeout 5m0s -t 4 -u https://t.me/c/3081142751/2970 -d G:\Software\TDL\downloads --skip-same

echo.
echo ========================================
echo Download completed!
echo ========================================
echo.
pause
