"""
Batch file generator for Telegram Downloader
Generates .bat files based on configuration settings
"""

import os
from pathlib import Path
from typing import List
from .config_manager import FullConfig


class BatchGenerator:
    """Generates Windows batch files for tdl execution"""

    def __init__(self):
        self.batch_filename = "telegram_downloader.bat"
        self.current_dir = Path.cwd()
        self.bin_dir = self.current_dir / "bin"
        self.tdl_path = self.bin_dir / "tdl.exe"

    def generate_batch(self, config: FullConfig) -> tuple[bool, str]:
        """
        Generate a batch file based on the provided configuration

        Args:
            config: Full configuration object

        Returns:
            Tuple of (success: bool, message: str)
        """
        try:
            # Validate configuration first
            errors = config.validate()
            if errors:
                return False, "Configuration validation failed:\n" + "\n".join(f"• {error}" for error in errors)

            # Generate command arguments
            command_args = config.get_command_args()

            # Create batch file content
            batch_content = self._create_batch_content(command_args)

            # Write batch file
            batch_path = self.current_dir / self.batch_filename
            with open(batch_path, 'w', encoding='utf-8') as f:
                f.write(batch_content)

            return True, f"Batch file '{self.batch_filename}' generated successfully!"

        except Exception as e:
            return False, f"Error generating batch file: {str(e)}"

    def _create_batch_content(self, command_args: List[str]) -> str:
        """Create the content for the batch file"""

        # Join command arguments with proper escaping
        command_parts = []
        for arg in command_args:
            # Escape special Windows batch characters
            if ' ' in arg and not arg.startswith('"'):
                arg = f'"{arg}"'
            command_parts.append(arg)

        command = ' '.join(command_parts)

        batch_content = f"""@echo off
chcp 65001 >nul
title Telegram Downloader - TDL GUI Generated

echo ========================================
echo  Telegram Downloader
echo  Generated by TDL GUI
echo ========================================
echo.
echo Command to execute:
echo {command}
echo.
echo Starting download...
echo.

{command}

echo.
echo ========================================
echo Download completed!
echo ========================================
echo.
pause
"""
        return batch_content

    def get_preview_command(self, config: FullConfig) -> str:
        """
        Get a preview of the command that will be generated

        Args:
            config: Full configuration object

        Returns:
            String representation of the command
        """
        try:
            command_args = config.get_command_args()
            return ' '.join(f'"{arg}"' if ' ' in arg else arg for arg in command_args)
        except Exception as e:
            return f"Error generating preview: {str(e)}"

    def validate_tdl_executable(self) -> tuple[bool, str]:
        """
        Check if tdl.exe exists in the bin directory

        Returns:
            Tuple of (exists: bool, message: str)
        """
        if self.tdl_path.exists():
            return True, f"tdl.exe found at: {self.tdl_path}"
        else:
            return False, f"tdl.exe not found in bin directory: {self.bin_dir}"

    def get_batch_file_path(self) -> str:
        """Get the full path where the batch file will be generated"""
        return str(self.current_dir / self.batch_filename)