"""
Batch file generator for Telegram Downloader
Generates .bat files based on configuration settings
"""

import os
import subprocess
from pathlib import Path
from typing import List, Tuple
from .config_manager import FullConfig


class BatchGenerator:
    """Generates Windows batch files for tdl execution"""

    def __init__(self):
        self.batch_filename = "telegram_downloader.bat"
        self.current_dir = Path.cwd()
        self.bin_dir = self.current_dir / "bin"
        self.tdl_path = self.bin_dir / "tdl.exe"

    def generate_batch(self, config: FullConfig, auto_close: bool = False) -> tuple[bool, str]:
        """
        Generate a batch file based on the provided configuration

        Args:
            config: Full configuration object
            auto_close: If True, the batch file will close automatically after completion

        Returns:
            Tuple of (success: bool, message: str)
        """
        try:
            # Validate configuration first
            errors = config.validate()
            if errors:
                return False, "Configuration validation failed:\n" + "\n".join(f"• {error}" for error in errors)

            # Generate command arguments
            command_args = config.get_command_args()

            # Create batch file content
            batch_content = self._create_batch_content(command_args, auto_close=auto_close)

            # Write batch file
            batch_path = self.current_dir / self.batch_filename
            with open(batch_path, 'w', encoding='utf-8') as f:
                f.write(batch_content)

            return True, f"Batch file '{self.batch_filename}' generated successfully!"

        except Exception as e:
            return False, f"Error generating batch file: {str(e)}"

    def _create_batch_content(self, command_args: List[str], auto_close: bool = False) -> str:
        """Create the content for the batch file

        Args:
            command_args: List of command arguments
            auto_close: If True, skip the pause command at the end
        """

        # Join command arguments with proper escaping
        command_parts = []
        for arg in command_args:
            # Escape special Windows batch characters
            if ' ' in arg and not arg.startswith('"'):
                arg = f'"{arg}"'
            command_parts.append(arg)

        command = ' '.join(command_parts)

        # Build batch content
        if auto_close:
            batch_content = f"""@echo off
chcp 65001 >nul
title Telegram Downloader - TDL GUI (Auto-close)

echo ========================================
echo  Telegram Downloader
echo  Generated by TDL GUI (Quick Run)
echo ========================================
echo.
echo Command to execute:
echo {command}
echo.
echo Starting download...
echo.

{command}

echo.
echo ========================================
echo Download completed! Closing in 3 seconds...
echo ========================================
timeout /t 3 /nobreak >nul
exit
"""
        else:
            batch_content = f"""@echo off
chcp 65001 >nul
title Telegram Downloader - TDL GUI Generated

echo ========================================
echo  Telegram Downloader
echo  Generated by TDL GUI
echo ========================================
echo.
echo Command to execute:
echo {command}
echo.
echo Starting download...
echo.

{command}

echo.
echo ========================================
echo Download completed!
echo ========================================
echo.
pause
"""
        return batch_content

    def get_preview_command(self, config: FullConfig) -> str:
        """
        Get a preview of the command that will be generated

        Args:
            config: Full configuration object

        Returns:
            String representation of the command
        """
        try:
            command_args = config.get_command_args()
            return ' '.join(f'"{arg}"' if ' ' in arg else arg for arg in command_args)
        except Exception as e:
            return f"Error generating preview: {str(e)}"

    def validate_tdl_executable(self) -> tuple[bool, str]:
        """
        Check if tdl.exe exists in the bin directory

        Returns:
            Tuple of (exists: bool, message: str)
        """
        if self.tdl_path.exists():
            return True, f"tdl.exe found at: {self.tdl_path}"
        else:
            return False, f"tdl.exe not found in bin directory: {self.bin_dir}"

    def get_batch_file_path(self) -> str:
        """Get the full path where the batch file will be generated"""
        return str(self.current_dir / self.batch_filename)

    def check_login_status(self) -> Tuple[bool, str]:
        """
        Check if tdl is logged in by trying to run a simple command.
        Uses 'tdl version' as a quick test - if session data exists and is valid,
        we assume logged in.

        Returns:
            Tuple of (logged_in: bool, message: str)
            - logged_in: True if logged in successfully
            - message: Status message or error description
        """
        if not self.tdl_path.exists():
            return False, f"tdl.exe not found at: {self.tdl_path}"

        # Check if session data exists
        session_path = Path.home() / ".tdl" / "data"
        if session_path.exists():
            # Session data exists, check if it has content
            try:
                session_files = list(session_path.glob("*"))
                if session_files:
                    return True, "Session data found - logged in"
            except Exception:
                pass

        return False, "Not logged in - no session data found"

    def validate_telegram_path(self, telegram_path: str) -> Tuple[bool, str]:
        """
        Validate Telegram Desktop path before login

        Args:
            telegram_path: Path to Telegram Desktop installation directory

        Returns:
            Tuple of (valid: bool, message: str)
        """
        telegram_dir = Path(telegram_path)
        if not telegram_dir.exists():
            return False, f"Telegram Desktop path does not exist: {telegram_path}"

        # Check for tdata directory (Telegram Desktop data directory)
        tdata_dir = telegram_dir / "tdata"
        if not tdata_dir.exists():
            return False, f"tdata directory not found in: {telegram_path}\nPlease select the Telegram Desktop installation directory."

        return True, "Path valid"

    def get_login_command(self, telegram_path: str) -> List[str]:
        """
        Get the login command arguments

        Args:
            telegram_path: Path to Telegram Desktop installation directory

        Returns:
            List of command arguments
        """
        return [str(self.tdl_path), "login", "-d", str(telegram_path)]

    # ── Export ──────────────────────────────────────────────────────

    def get_export_preview_command(self, export_cfg, session_cfg) -> str:
        """Return a human-readable preview of the export command."""
        try:
            args = export_cfg.get_command_args(session_cfg)
            return ' '.join(f'"{a}"' if ' ' in a else a for a in args)
        except Exception as e:
            return f"Error generating preview: {e}"

    def generate_export_batch(self, export_cfg, session_cfg,
                              auto_close: bool = False) -> tuple[bool, str]:
        """Generate a .bat file for the export command."""
        errors = export_cfg.validate()
        if errors:
            return False, "配置校验失败:\n" + "\n".join(f"• {e}" for e in errors)
        try:
            args = export_cfg.get_command_args(session_cfg)
            command_parts = []
            for arg in args:
                if ' ' in arg and not arg.startswith('"'):
                    arg = f'"{arg}"'
                command_parts.append(arg)
            command = ' '.join(command_parts)

            if auto_close:
                content = (
                    "@echo off\nchcp 65001 >nul\n"
                    "title TDL 消息导出 (Auto-close)\n\n"
                    "echo ========================================\n"
                    "echo  TDL 消息导出\n"
                    "echo  Generated by TDL GUI\n"
                    "echo ========================================\n"
                    "echo.\n"
                    f"echo {command}\necho.\n\n"
                    f"{command}\n\n"
                    "echo.\necho 导出完成，3 秒后关闭…\n"
                    "timeout /t 3 /nobreak >nul\nexit\n"
                )
            else:
                content = (
                    "@echo off\nchcp 65001 >nul\n"
                    "title TDL 消息导出 - TDL GUI\n\n"
                    "echo ========================================\n"
                    "echo  TDL 消息导出\n"
                    "echo  Generated by TDL GUI\n"
                    "echo ========================================\n"
                    "echo.\n"
                    f"echo {command}\necho.\n\n"
                    f"{command}\n\n"
                    "echo.\necho ========================================\n"
                    "echo 导出完成！\n"
                    "echo ========================================\n"
                    "echo.\npause\n"
                )

            bat_path = self.current_dir / "tdl_export.bat"
            with open(bat_path, 'w', encoding='utf-8') as f:
                f.write(content)
            return True, f"批处理文件 'tdl_export.bat' 已生成！"
        except Exception as e:
            return False, f"生成批处理文件时出错: {e}"