@echo off
chcp 65001 >nul
title Telegram Downloader - TDL GUI Generated

echo ========================================
echo  Telegram Downloader
echo  Generated by TDL GUI
echo ========================================
echo.
echo Command to execute:
echo tdl dl -l 1 -n default --pool 8 --proxy socks5://127.0.0.1:7897 --reconnect-timeout 5m0s -t 1 -u https://t.me/c/3081142751/2998 -u https://t.me/c/3081142751/2999 -u https://t.me/c/3081142751/3000 -d G:\Software\TDL\downloads
echo.
echo Starting download...
echo.

tdl dl -l 1 -n default --pool 8 --proxy socks5://127.0.0.1:7897 --reconnect-timeout 5m0s -t 1 -u https://t.me/c/3081142751/2998 -u https://t.me/c/3081142751/2999 -u https://t.me/c/3081142751/3000 -d G:\Software\TDL\downloads

echo.
echo ========================================
echo Download completed!
echo ========================================
echo.
pause
